# Generated by Django 2.1.4 on 2019-01-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanKeuangan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.BigIntegerField()),
                ('inventory', models.BigIntegerField()),
                ('current_asset', models.BigIntegerField()),
                ('fixed_asset', models.BigIntegerField()),
                ('total_asset', models.BigIntegerField()),
                ('current_liabilities', models.BigIntegerField()),
                ('long_term_liabilities', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('outstanding_share', models.BigIntegerField()),
                ('total_equity', models.BigIntegerField()),
                ('total_revenue', models.BigIntegerField()),
                ('gross_profit', models.BigIntegerField()),
                ('operating_profit', models.BigIntegerField()),
                ('interest_expense', models.BigIntegerField()),
                ('net_profit', models.BigIntegerField()),
                ('earnings_per_share', models.IntegerField()),
                ('dividend_payment', models.BigIntegerField()),
                ('stock_price', models.IntegerField()),
                ('kurs_rupiah_dollar', models.IntegerField()),
                ('year', models.CharField(choices=[('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('kd_perusahaan', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_perusahaan', models.CharField(max_length=50)),
                ('deskripsi_perusahaan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SektorPerusahaan',
            fields=[
                ('kd_sektor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_sektor', models.CharField(max_length=50)),
                ('deskripsi_sektor', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='kd_sektor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_sektor_perusahaan', to='financialperformance.SektorPerusahaan'),
        ),
        migrations.AddField(
            model_name='laporankeuangan',
            name='kd_perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_perusahaan', to='financialperformance.Perusahaan'),
        ),
    ]
