# Generated by Django 2.1.4 on 2019-01-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialperformance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('company_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('sector_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sector_name', models.CharField(max_length=50)),
                ('sector_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013')], max_length=4)),
                ('cash', models.BigIntegerField()),
                ('inventory', models.BigIntegerField()),
                ('current_asset', models.BigIntegerField()),
                ('fixed_asset', models.BigIntegerField()),
                ('total_asset', models.BigIntegerField()),
                ('current_liabilities', models.BigIntegerField()),
                ('long_term_liabilities', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('outstanding_share', models.BigIntegerField()),
                ('total_equity', models.BigIntegerField()),
                ('total_revenue', models.BigIntegerField()),
                ('gross_profit', models.BigIntegerField()),
                ('operating_profit', models.BigIntegerField()),
                ('interest_expense', models.BigIntegerField()),
                ('net_profit', models.BigIntegerField()),
                ('earnings_per_share', models.IntegerField()),
                ('dividend_payment', models.BigIntegerField()),
                ('stock_price', models.IntegerField()),
                ('exchange_rate_rupiah_dollar', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_company_to_financialperformance', to='financialperformance.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='laporankeuangan',
            name='kd_perusahaan',
        ),
        migrations.RemoveField(
            model_name='perusahaan',
            name='kd_sektor',
        ),
        migrations.DeleteModel(
            name='LaporanKeuangan',
        ),
        migrations.DeleteModel(
            name='Perusahaan',
        ),
        migrations.DeleteModel(
            name='SektorPerusahaan',
        ),
        migrations.AddField(
            model_name='company',
            name='company_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_companysector_to_company', to='financialperformance.CompanySector'),
        ),
    ]
