# Generated by Django 2.1.4 on 2019-01-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialperformance', '0002_auto_20190105_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013')], max_length=4)),
                ('cash', models.BigIntegerField()),
                ('inventory', models.BigIntegerField()),
                ('current_asset', models.BigIntegerField()),
                ('fixed_asset', models.BigIntegerField()),
                ('total_asset', models.BigIntegerField()),
                ('current_liabilities', models.BigIntegerField()),
                ('long_term_liabilities', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('outstanding_share', models.BigIntegerField()),
                ('total_equity', models.BigIntegerField()),
                ('total_revenue', models.BigIntegerField()),
                ('gross_profit', models.BigIntegerField()),
                ('operating_profit', models.BigIntegerField()),
                ('interest_expense', models.BigIntegerField()),
                ('net_profit', models.BigIntegerField()),
                ('earnings_per_share', models.IntegerField()),
                ('dividend_payment', models.BigIntegerField()),
                ('stock_price', models.IntegerField()),
                ('exchange_rate_rupiah_dollar', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_company_to_financialstatement', to='financialperformance.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='financialperformance',
            name='company',
        ),
        migrations.DeleteModel(
            name='FinancialPerformance',
        ),
    ]
