# Generated by Django 2.1.4 on 2019-01-05 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialperformance', '0003_auto_20190105_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_companysectors_to_company', to='financialperformance.CompanySector'),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_companys_to_financialstatement', to='financialperformance.Company'),
        ),
    ]
