# Generated by Django 2.1.4 on 2019-01-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialperformance', '0004_auto_20190105_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysector',
            name='sector_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
