# Generated by Django 2.1.4 on 2019-01-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialperformance', '0007_company_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='earnings_per_share',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
