# Generated by Django 2.1.4 on 2019-01-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialperformance', '0008_auto_20190117_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='earnings_per_share',
            field=models.FloatField(),
        ),
    ]
