# Generated by Django 2.1.4 on 2019-01-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialperformance', '0009_auto_20190117_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysector',
            name='sector_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
