# Generated by Django 2.1.4 on 2019-01-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialperformance', '0010_companysector_sector_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='exchange_rate_rupiah_dollar',
            field=models.CharField(choices=[('dollar', 'dollar'), ('rupiah', 'rupiah')], max_length=6),
        ),
    ]
